- name: Configure switches
  hosts: all
  gather_facts: False
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset: "network"

    - name: Print facts
      debug:
        var: ansible_facts
        verbosity: 1