---
- name: Configure devices
  hosts: leaf01, leaf02, spine01, server01, server02, server03
  gather_facts: false
  become: yes
  tasks:
    - name: Interface tasks
      include_tasks:
        file: tasks/interfaces.yml

    - name: Server tasks
      include_tasks:
        file: tasks/server.yml
      when: "'server' in inventory_hostname"
