interfaces:
  physicals:
    - name: eth1
      description: leaf01
      address: 192.168.2.31/24
      enabled: true

    - name: eth2
      description: leaf02
      address: 192.168.2.32/24
      enabled: true
